name: Create Release

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci-checks:
    uses: ./.github/workflows/partial-ci-checks.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: ci-checks
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up uv (package manager)
        uses: astral-sh/setup-uv@v6

      - name: Build extension
        run: just build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.ci-checks.outputs.version }}
          name: Release v${{ needs.ci-checks.outputs.version }}
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
