name: Create Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up uv (package manager)
        uses: astral-sh/setup-uv@v6

      - name: Version check
        id: version
        uses: ./.github/actions/version-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv (package manager)
        uses: astral-sh/setup-uv@v6

      - name: Install Python dependencies
        run: uv sync --locked

      - name: Lint
        run: uv run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv (package manager)
        uses: astral-sh/setup-uv@v6

      - name: Install Python dependencies
        run: uv sync --locked

      - name: Test
        run: uv run pytest

  release:
    runs-on: ubuntu-latest
    needs: [version-check, lint, test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up uv (package manager)
        uses: astral-sh/setup-uv@v6

      - name: Build extension
        run: uv build --wheel

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.version-check.outputs.version }}
          name: Release v${{ needs.version-check.outputs.version }}
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
